# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 赵阳
  params:
    description: 个人介绍
  menu:
    main:
      - name: 个人介绍
        url: '#about'
        weight: 10
      - name: 专著
        url: '#post'
        weight: 20
      - name: 论文
        url: '#publications'
        weight: 30
      - name: 学术活动
        url: '#project'
        weight: 40
